problem 6_1
sporadicCactus/MADE_alg_homework pull request #1
Opened 2019-11-21 08:56 UTC by sporadicCactus

2019-11-22 02:01 UTC, ylyubimov requested changes

2019-11-22 02:01 UTC, ylyubimov commented on pr_6_1.cpp
> +        Node *parent;
в задаче 6 parent лишний

2019-11-22 02:01 UTC, ylyubimov commented on pr_6_1.cpp
> +        BTree(Node *node);
А деструктор?

2019-11-22 02:01 UTC, ylyubimov commented on pr_6_1.cpp
> +            if (rc != NULL) {going_down = true; stack.push_back(rc);}
!rc

2019-11-22 02:02 UTC, ylyubimov commented
Добавь деструктор. Ссылку на контест. И перепризови меня на ревью, чтобы я нотификацию увидел.

2019-11-22 14:50 UTC, sporadicCactus commented
Контест: https://contest.yandex.ru/contest/15368/run-report/26467615/

2019-11-22 14:55 UTC, sporadicCactus commented on pr_6_1.cpp
> +        BTree(Node *node);
Добавил

2019-11-22 15:05 UTC, sporadicCactus commented
По поводу деструктора. Я решил поэксперементировать и сделать класс дерева как обёртку --- т.е. иметь возможность создавать объекты деревьев, которые являются поддеревьями исходного, применять к ним методы класса дерева (split, merge, insert, ...), а затем выбрасывать эти объекты. Соответственно, деструктор не должен удалять узлы, иначе он будет портить исходное дерево. Во второй задаче в дереве есть отдельный метод для удаления (в смысле освобождения памяти) всех узлов.

2019-11-26 23:51 UTC, ylyubimov approved these changes

2019-11-26 23:51 UTC, ylyubimov commented on pr_6_1.cpp
> +    root = NULL;
Это ничего не удаляет.

2019-11-26 23:51 UTC, ylyubimov commented on pr_6_1.cpp
> +    tree.traverse_preorder(&print_key, NULL);
Тогда верни, как было print and delete, видимо действительно его не заметил сначала.
Но деструктор было бы правильнее сделать

2019-11-27 10:21 UTC, merged