problem 19
sporadicCactus/MADE_alg_homework pull request #13
Opened 2019-12-30 23:51 UTC by sporadicCactus

Контест: https://contest.yandex.ru/contest/16362/run-report/29363055/
В данной реализации неэффективно используется память: весь список, каким прямоугольникам принадлежит ячейка, хранится к листьях дерева, а не разбросан по его узлам. Контест проходится, но оптимизировать этот момент не успел.

2020-01-07 16:11 UTC, ylyubimov requested changes
Кажется, подразумевалось, что у тебя есть множество точек и нужно уметь отвечать на вопрос: Сколько точек содержится в прямоугольнике? 
А у тебя решается обратная задача, ты сначала просто запоминаешь точки, потом получаешь все "ЗАПРОСЫ" с прямоугольниками, а потом в них накидываешь точки. Это не правильно

2020-01-07 16:11 UTC, ylyubimov commented on pr_19.cpp
> +        counter.AddBox(Box(round_x(x_left), round_y(y_left), round_x(x_right), round_y(y_right)));
почему идет округление к целым числам?

2020-01-07 16:11 UTC, ylyubimov commented on pr_19.cpp
> +        if (!empty) return;
Это одно разовый метод?
Я не смогу потом вызвать для других значений?

2020-01-12 22:55 UTC, sporadicCactus commented on pr_19.cpp
> +        if (!empty) return;
Здесь дерево строилось раз и навсегда. Для новых значений нужно создавать новый объект.

2020-01-12 23:01 UTC, sporadicCactus commented on pr_19.cpp
> +        counter.AddBox(Box(round_x(x_left), round_y(y_left), round_x(x_right), round_y(y_right)));
Основная причина --- потому что могу :) Масштаб в задаче заранее известен.
С целыми проще работать, нет проблем с ассоциативностью, ведут себя более предсказуемо.
Ну и числа с плавающей точкой неравномерно распределены в заданной области. Кажется более вероятным, что точность везде нужна одинаковая.

2020-01-13 22:56 UTC, ylyubimov approved these changes
Сейчас уже смотреть не буду). Ты проверь в контесте, что задача проходит. Кажется, курс у нас уже заканчивается. Спасибо за семестр.

2020-01-17 09:26 UTC, merged