problem 7_3
sporadicCactus/MADE_alg_homework pull request #2
Opened 2019-11-21 08:58 UTC by sporadicCactus

2019-11-22 15:09 UTC, sporadicCactus commented
Ссылка на контест: https://contest.yandex.ru/contest/15368/run-report/26465324/

По поводу деструктора откомментировал в задаче 6_1. Здесь его роль играет метод wipe_nodes.

2019-11-27 22:52 UTC, ylyubimov requested changes
Это пока первые замечания

2019-11-27 22:52 UTC, ylyubimov commented on pr_7_3.cpp
> +        Node *parent;
parent тебе не нужен
Он нужен только в Splay дереве и то без него можно обойтись, но в декартовом он только мешает

2019-11-27 22:52 UTC, ylyubimov commented on pr_7_3.cpp
> +        void push_back(void *num);
Может просто сделать очередь шаблонной? Чтобы указатели на * не передавать?

2019-11-27 22:52 UTC, ylyubimov commented on pr_7_3.cpp
> +        int len();
const

2019-11-27 22:52 UTC, ylyubimov commented on pr_7_3.cpp
> +        ~Deque();
правило пяти

2019-11-27 22:52 UTC, ylyubimov commented on pr_7_3.cpp
> +        void insert(int key, int priority);
приоритет нужно генерировать внутри дерева
Пользователю должно быть неважно, какое дерево перед ним

2019-11-29 20:07 UTC, sporadicCactus commented on pr_7_3.cpp
> +        int len();
Сделал const, но в чём разница? Компилятору проще оптимизировать циклы?

2019-12-04 23:51 UTC, ylyubimov commented on pr_7_3.cpp
> +        int len();
нет, можно вызвать у неконстантного объекта. Узнать, например, у очереди сколько в ней объектов.

2019-12-04 23:58 UTC, ylyubimov commented
> Насколько затратно звать new/delete при большом количестве узлов в дереве? В случае, когда размер узла известен заранее (как здесь), имеет ли смысл писать собственный аллокатор для узлов?
Операции аллокации памяти действительно очень неприятны. Здесь можно было бы написать свой аллокатор, например выделяя блоки большого размера кратного размеру узла. Но это имеет смысл, когда у тебя 10ки тысяч аллокаций. Иначе эффект будет не особо ощутим. 
В общем на практике оптимизировать надо лишь в том случае, если уже ощущаешь проблемы, либо точно знаешь, что они будут.

2019-12-04 23:58 UTC, ylyubimov approved these changes

2019-12-04 23:58 UTC, ylyubimov commented on pr_7_3.cpp
> +        void push_back(T item);
Вот тут не будет копирования элемента T лишний раз? он может быть довольно большой

2019-12-04 23:58 UTC, ylyubimov commented on pr_7_3.cpp
> +        const int len();
const не там написал)
нужно
int len() const;)))

2019-12-05 16:31 UTC, merged