problem 8_1
sporadicCactus/MADE_alg_homework pull request #3
Opened 2019-11-27 10:34 UTC by sporadicCactus

Контест: https://contest.yandex.ru/contest/15766/run-report/27144559/

Размер ячейки в байтах задаётся числом \in_place_bytes. Короткие строки (длина < \in_place_bytes) хранятся прямо в таблице, длинные -- в отдельном буфере, в таблице хранится указатель. Строки хранятся как последовательность ASCII символов без \0 окончания.
 
Первый байт каждой ячейки таблицы описывает состояние ячейки:
0x00 -- ячейка свободна.
0x01 - 0xEF -- строка храниться прямо в ячейке, значение байта --- длина строки.
0xF0 -- строка удалена.
0xFF -- следующие sizeof(void*) байт хранят указатель на буфер со строкой. В первых байтах буфера лежит int с длиной строки, следующие байты -- символы.

Таблица перехешируется при наполненности более 3/4, при этом размер таблицы удваивается, если более половины таблицы заполнено действительными (не удалёнными) строками.

2019-12-04 22:17 UTC, ylyubimov requested changes

2019-12-04 22:17 UTC, ylyubimov commented on pr_8_1.cpp
> +    ~HashTable();
Тут правила 5ти не хвататет

2019-12-04 22:17 UTC, ylyubimov commented on pr_8_1.cpp
> +    bool Has(std::string key);
Вот эта пара должна быть const

2019-12-04 22:17 UTC, ylyubimov commented on pr_8_1.cpp
> +    if (key.len < 1) return -1;
Чем эта функция отличается от FindSlot?

2019-12-04 22:17 UTC, ylyubimov commented on pr_8_1.cpp
> +    throw std::logic_error("The table is full!");
Кажется при записи надо возвращать индекс первой встреченной удаленной ячейки (если такая есть), при это обязательно доходить до конца, чтобы не было повторов

2019-12-05 16:33 UTC, sporadicCactus commented on pr_8_1.cpp
> +    throw std::logic_error("The table is full!");
Действительно, так будет меньше перехеширований :) Поправил.

2019-12-05 16:35 UTC, sporadicCactus commented on pr_8_1.cpp
> +    if (key.len < 1) return -1;
Find выдаёт индекс ячейки, где хранится ключ, и -1, если ключа нигде нет. FindSlot выдаёт индекс ячейки, куда можно записать ключ, и -1, если если такой ключ уже есть.

2019-12-05 21:43 UTC, ylyubimov approved these changes

2019-12-06 09:10 UTC, merged