problem 14
sporadicCactus/MADE_alg_homework pull request #8
Opened 2019-12-20 07:40 UTC by sporadicCactus

Контест: https://contest.yandex.ru/contest/16185/run-report/29106996/

2019-12-29 22:45 UTC, ylyubimov requested changes
Пока 3 балла

2019-12-29 22:45 UTC, ylyubimov commented on pr_14_1.cpp
> +    arrow(int target_, int w_): target_node(target_), weight(w_) {}
Что за стрела? Ребро?

2019-12-29 22:45 UTC, ylyubimov commented on pr_14_1.cpp
> +struct node_with_neighbour {
Это второе название для ребра?

2019-12-29 22:45 UTC, ylyubimov commented on pr_14_1.cpp
> +            front.push(new_front_node);
В очереди не должно быть дубликтов. Старые значения для этой же вершины нужно удалять.

2019-12-31 00:09 UTC, sporadicCactus commented on pr_14_1.cpp
> +    arrow(int target_, int w_): target_node(target_), weight(w_) {}
Ребро, но ассиметричное -- с информацией только об одном узле (цели). Потому назвал стрелкой.

2019-12-31 00:11 UTC, sporadicCactus commented on pr_14_1.cpp
> +struct node_with_neighbour {
Да, в данном контексте это особое ребро --- кратчайшее до дерева (в некоторый момент). Потому назвал как узел с ближайшим соседом (из дерева).

2019-12-31 00:16 UTC, sporadicCactus commented on pr_14_1.cpp
> +            front.push(new_front_node);
Я поступил здесь немного иначе --- дубликаты не удаляю, а просто отбрасываю, когда они всплывают вверх. Ко времени их всплытия узел, который они предлагают, уже добавлен --- это я и проверяю.
Получается, используется больше памяти, но время работы (по моим наблюдениям) сокращается. Вместо поиска дубликата в дереве (упорядоченном множестве) я делаю проверку в массиве булов (за O(1)). Ну и куча быстрее дерева, поэтому очередь работает быстрее. Или я чего-то не понимаю?

2020-01-07 16:26 UTC, ylyubimov commented on pr_14_1.cpp
> +            front.push(new_front_node);
Куча вроде асимптотически не быстрее
в вот логарифм у тебя получается от большего значения, если из кучи элементы не удалять. Поэтому асимптотика станет хуже

2020-01-07 16:30 UTC, ylyubimov requested changes
Ты, конечно, не ищешь простых путей.
В общем, обрати внимание на то, что код, который ты производишь довольно сложен. Я поставлю тебе 5 баллов за эту задачу, и, скорее всего, ты получишь 5 баллов за курс (заслуженно).
Но на будущее старайся писать проще, предполагай, что тебя будет читать простой разработчик без большого опыта. Лучше разбивай решение на функции, пиши комментарии к тем местам, где можно тебя неправильно понять, особенно к тем, где ты отклоняешься от стандартных алгоритмов, объясняй почему ты так делаешь.
Спасибо. И с Рождеством!

2020-01-07 16:30 UTC, ylyubimov approved these changes

2020-01-10 18:27 UTC, merged